# Generated by Django 4.0 on 2022-06-29 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_user_displaypicture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='displaypicture',
        ),
    ]
